=== propelorm/Propel2/resources/dtd/database.dtd
<!--
    Propel XML database schema DTD
    $Id: database.dtd,v 1.7 2005/03/30 11:38:18 hlellelid Exp $

    This is based very closely on the schema DTD for Torque, but
    some differences do exist.
-->

<!--

defaultPhpNamingMethod determines how a table or column name,
from the name attribute in the xml database file, is converted to a
PHP class or method name.

     nochange   - indicates not change is performed.
     underscore - Underscores are removed, First letter is
              capitalized, first letter after an underscore
              is capitalized, the rest of the letters are
              converted to lowercase.
     phpname   - same as underscore, but no letters are converted
              to lowercase.
-->

<!ELEMENT database (external-schema*, entity+, behavior*)>
<!ATTLIST database
  name CDATA #IMPLIED
  defaultIdMethod (native|none) "none"
  package CDATA #IMPLIED
  schema CDATA #IMPLIED
  namespace CDATA #IMPLIED
  baseClass CDATA #IMPLIED
  defaultPhpNamingMethod (nochange|underscore|phpname) "underscore"
  heavyIndexing (true|false) "false"
  identifierQuoting (true|false) "false"
  tablePrefix CDATA #IMPLIED
  defaultStringFormat CDATA #IMPLIED
  xmlns:xsi CDATA #IMPLIED
  xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>

<!ELEMENT external-schema EMPTY>
<!ATTLIST external-schema
  filename CDATA #REQUIRED
>

<!--
     note: the interface="true", requires that useManagers=true in the
     properties file.
-->
<!ELEMENT entity (field+,(relation|index|unique|id-method-parameter|behavior|vendor)*)>
<!ATTLIST entity
  name CDATA #REQUIRED
  tableName CDATA #IMPLIED
  idMethod (native|autoincrement|sequence|none|null) "null"
  skipSql (true|false) "false"
  readOnly (true|false) "false"
  abstract (true|false) "false"
  isCrossRef (true|false) "false"
  allowPkInsert (true|false) "false"
  package CDATA #IMPLIED
  schema CDATA #IMPLIED
  namespace CDATA #IMPLIED
  baseClass CDATA #IMPLIED
  alias CDATA #IMPLIED
  interface CDATA #IMPLIED
  tableNamingMethod (nochange|underscore|phpname) #IMPLIED
  heavyIndexing (true|false) #IMPLIED
  identifierQuoting (true|false) #IMPLIED
  description CDATA #IMPLIED
  defaultStringFormat CDATA #IMPLIED
>

<!ELEMENT id-method-parameter EMPTY>
<!ATTLIST id-method-parameter
  name CDATA "default"
  value CDATA #REQUIRED
>

<!ELEMENT field ((inheritance|vendor)*)>
<!ATTLIST field
  name CDATA #REQUIRED
  primaryKey (true|false) "false"
  required (true|false) "false"
  type
    (
          BIT    | TINYINT | SMALLINT    | INTEGER    | BIGINT    | FLOAT
        | REAL   | NUMERIC | DECIMAL     | CHAR       | VARCHAR   | LONGVARCHAR
        | DATE   | TIME    | TIMESTAMP   | BINARY     | VARBINARY | LONGVARBINARY
        | NULL   | OTHER   | PHP_OBJECT  | DISTINCT   | STRUCT    | ARRAY
        | BLOB   | CLOB    | REF         | BOOLEANINT | BOOLEANCHAR
        | DOUBLE | BOOLEAN | OBJECT      | ENUM
    ) "VARCHAR"
  phpType CDATA #IMPLIED
  sqlType CDATA #IMPLIED
  size CDATA #IMPLIED
  scale CDATA #IMPLIED
  default CDATA #IMPLIED
  defaultValue CDATA #IMPLIED
  defaultExpr CDATA #IMPLIED
  autoIncrement (true|false) "false"
  inheritance (single|false) "false"
  phpNamingMethod (nochange|underscore|phpname) #IMPLIED
  description CDATA #IMPLIED
  lazyLoad (true|false) "false"
  primaryString (true|false) "false"
  valueSet CDATA #IMPLIED
>

<!ELEMENT inheritance EMPTY>
<!ATTLIST inheritance
  key CDATA #REQUIRED
  class CDATA #REQUIRED
  package CDATA #IMPLIED
  extends CDATA #IMPLIED
>

<!ELEMENT relation (reference*, vendor*)>
<!ATTLIST relation
  target CDATA #REQUIRED
  field CDATA #IMPLIED
  name CDATA #IMPLIED
  refFieldName CDATA #IMPLIED
  refName CDATA #IMPLIED
  onUpdate (CASCADE|cascade|SETNULL|setnull|RESTRICT|restrict|NONE|none) "none"
  onDelete (CASCADE|cascade|SETNULL|setnull|RESTRICT|restrict|NONE|none) "none"
  skipSql (true|false) "false"
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
  local CDATA #REQUIRED
  foreign CDATA #REQUIRED
>

<!ELEMENT index (index-field+,vendor*)>
<!ATTLIST index
  name CDATA #IMPLIED
>

<!ELEMENT behavior (parameter*)>
<!ATTLIST behavior
  name CDATA #IMPLIED
>

<!ELEMENT index-field (vendor*)>
<!ATTLIST index-field
  name CDATA #REQUIRED
  size CDATA #IMPLIED
>

<!ELEMENT unique (unique-field+)>
<!ATTLIST unique
  name CDATA #IMPLIED
>

<!ELEMENT unique-field (vendor*)>
<!ATTLIST unique-field
  name CDATA #REQUIRED
>

<!ELEMENT vendor (parameter+)>
<!ATTLIST vendor
  type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

=== propelorm/Propel2/tests/Fixtures/quoting/schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "../dtd/database.dtd">

<database name="quoting" identifierQuoting="true" defaultIdMethod="native" namespace="Propel\Tests\Quoting">
    <entity name="QuotingGroup">
        <field name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER"/>
        <field name="title" type="VARCHAR" primaryString="true"/>
        <field name="by" type="VARCHAR" size="64"/>
        <field name="as" type="INTEGER" />
        <relation target="QuotingAuthor"/>
    </entity>
    <entity name="QuotingAuthor" identifierQuoting="false">
        <field name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER"/>
        <field name="name" type="VARCHAR" primaryString="true"/>
        <relation target="QuotingAuthorType" />
    </entity>
    <entity name="QuotingAuthorType">
        <field name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER"/>
        <field name="title" type="VARCHAR" primaryString="true"/>
    </entity>
</database>

=== propelorm/Propel2/tests/Fixtures/bookstore-packaged/review.schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "../dtd/database.dtd">

<database package="core.review" name="bookstore" defaultIdMethod="native" namespace="Propel\Tests\BookstorePackaged">

  <entity name="Review" description="Book Review">
    <behavior name="auto_add_pk" />
    <field name="reviewed_by" required="true" type="VARCHAR" size="128" description="Reviewer Name"/>
    <field name="review_date" required="true" type="DATE" default="2001-01-01" description="Date of Review"/>
    <field name="recommended" required="true" type="BOOLEAN" description="Does reviewer recommend book?"/>
    <field name="status" type="VARCHAR" size="8" description="The status of this review."/>
    <field name="book_id" required="true" type="INTEGER" description="Book ID for this review"/>
    <relation target="Book" onDelete="CASCADE">
      <reference local="book_id" foreign="id"/>
    </relation>
  </entity>

</database>

=== propelorm/Propel2/tests/Fixtures/bookstore-packaged/media.schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "../dtd/database.dtd">

<database package="core.book" name="bookstore" defaultIdMethod="native" namespace="Propel\Tests\BookstorePackaged">

  <!-- This table exists to explore/test the handling of BLOB/CLOB objects. -->
  <entity name="Media">
   <behavior name="auto_add_pk" />
    <field name="cover_image" type="BLOB" lazyLoad="true" description="The image of the book cover."/>
    <field name="excerpt" type="CLOB" lazyLoad="true" description="An excerpt from the book."/>
    <field name="book_id" required="true" type="INTEGER" description="Book ID for this media collection."/>
    <relation target="Book" onDelete="CASCADE">
        <reference local="book_id" foreign="id"/>
    </relation>
  </entity>

</database>

=== propelorm/Propel2/tests/Fixtures/bookstore-packaged/book_club_list.schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "../dtd/database.dtd">

<database package="addon.club" name="bookstore" defaultIdMethod="native" namespace="Propel\Tests\BookstorePackaged">

  <!-- this table exists to test the many-to-many -->
  <entity name="BookClubList" description="Reading list for a book club.">
    <behavior name="auto_add_pk" />
    <field
      name="groupLeader"
      required="true"
      type="VARCHAR"
      size="100"
      description="The name of the teacher in charge of summer reading."/>
    <field
      name="theme"
      required="false"
      type="VARCHAR"
      size="50"
      description="The theme, if applicable, for the reading list."/>
  </entity>

  <entity name="BookListRel" description="Cross-reference table for many-to-many relationship between book rows and book_club_list rows.">
    <field name="bookId" primaryKey="true" type="INTEGER" description="Fkey to book.id"/>
    <field name="bookClubListId" primaryKey="true" type="INTEGER" description="Fkey to book_club_list.id"/>
    <relation target="Book" onDelete="CASCADE">
      <reference local="bookId" foreign="id"/>
    </relation>
    <relation target="BookClubList" onDelete="CASCADE">
      <reference local="bookClubListId" foreign="id"/>
    </relation>
  </entity>

</database>
